### ISSUE TITLE
Requests post

### ISSUE THREAD

**Issue by csuarezgfx** [adafruit/Adafruit-Huzzah-ESP8266-Basic-Breakout-PCB#1]
I'd like to request  adafruit for a tutorial on how to reflash the HUZZAH. I make this request because my HUZZAH does not work out of the box with the Arduino IDE (1.6.5) nor PuTTY. It does not work on Linux nor Windows. I followed the simple tutorial Adafruit provides so it makes it all the more confusing when the errors print out and the sketches dont upload. There is not much information on how to resolve these issues on the HUZZAH so how about a troubleshooting HUZZAH blog post?

As for the errors I get when I try to upload a sketch, this is what they look like. When I merely connect the usb cable and open the serial monitor I see this: 
������l`Đ���n�$��r���nn�� b�l`$��r��l����l���b�$��r��l������b�$��r��l������b�$��r�����Ē������b����������l`Đ���n�$��r���nn�� b�l`$��r��l����l���b�$��r��l������b�$��r��l������b�$��r�����Ē������b����������l`Đ���n�$��r���nn�� 

infinitely.

When I try to upload the sketch after following the Adafruit instructions I get:

ck@atelier-klippel.de
    setting board to ck
    setting baudrate from 115200 to 115200
    setting port from /dev/ttyUSB0 to /dev/ttyUSB0
    setting address from 0x00000000 to 0x00000000
    espcomm_upload_file
    stat /tmp/build2111145911720418528.tmp/connect_to_server.cpp.bin success
opening port /dev/ttyUSB0 at 115200
    tcgetattr
    tcsetattr
    serial open
opening bootloader
resetting board
trying to connect
    setting character timeout 0
    done
    setting character timeout 1
    done
    espcomm_send_command: sending command header
    espcomm_send_command: sending command payload
trying to connect
    setting character timeout 0
    done
    setting character timeout 1
    done
    espcomm_send_command: sending command header
    espcomm_send_command: sending command payload
    serialport_receive_C0: 00 instead of C0
trying to connect
    setting character timeout 0
    done
    setting character timeout 1
    done
    espcomm_send_command: sending command header
    espcomm_send_command: sending command payload
    espcomm_send_command: receiving 2 bytes of data
    espcomm_open
Uploading 298320 bytes from /tmp/build2111145911720418528.tmp/connect_to_server.cpp.bin to flash at 0x00000000
    erasing flash
    size: 048d50 address: 000000
    first_sector_index: 0
    total_sector_count: 73
    head_sector_count: 16
    adjusted_sector_count: 57
    adjusted_size: 039000
    espcomm_send_command: sending command header
    espcomm_send_command: sending command payload
    setting timeout 10000
    setting character timeout 100
    done
    setting timeout 1
    setting character timeout 1
    done
    espcomm_send_command: receiving 2 bytes of data
    writing flash
................................................................................................................................... serialport_receive_C0: 00 instead of C0
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
    serialport_receive_C0: 2C instead of C0
warning: espcomm_send_command: didn't receive command response
closing bootloader

And that is where I find myself for now. Has anyone else received these errors?

**Comment by tdicola** [comment]
Are you sure the USB to serial cable that you're using is working correctly?  Try connecting to an Arduino and using a software serial connection to send and receive data with the cable: https://www.arduino.cc/en/Reference/SoftwareSerial  That way you can check it's reading and writing values as you expect.  

Or a simpler but less comprehensive test is to connect the cable's RX pin to its TX pin and then open the serial terminal at any baud, you should see whatever you type echoed back to you.  

If that's still not working email support@adafruit.com with info on the ESP that's having trouble and they should be able to help troubleshoot and get a replacement if it's broken.  Thanks!

**Comment by csuarezgfx** [comment]
Thanks tdicola. The error was on my side. I was letting go of both buttons at the same time which was putting the ESP in that locked state. Adafruit has since then updated their tutorial with a more detailed explanation of the button sequence.
