### ISSUE TITLE
Bootload mode issues

### ISSUE THREAD

**Issue by TAlbarran** [adafruit/Adafruit-Huzzah-ESP8266-Basic-Breakout-PCB#2]
I have been testing the board with some Arduino code.  It worked without issues for a couple of days until suddenly I had issues running the bootload on the device.  Whenever I flash new code onto the board, the code runs for a couple of seconds until the blue LED flashes and the board reverts back to bootload mode.  Any ideas why this is happening?

**Comment by ladyada** [comment]
tech support is done in the forums, not github. thx!
