### ISSUE TITLE
Cannot open SCH and BRD files in Eagle

### ISSUE THREAD

**Issue by ngmacha** [adafruit/Adafruit-Huzzah-ESP8266-Basic-Breakout-PCB#3]
Eagle version 9.6.2 gives error "line 8, column 87: This is not an EAGLE file" when trying to open the files. What could be a problem?

**Comment by ladyada** [comment]
https://forums.autodesk.com/t5/eagle-forum/how-to-fix-error-quot-line-8-column-16-this-is-not-an-eagle-file/td-p/7839653
